title: 苏南生

name: 苏南生的博客
description:   A Oracle EBS Technology
url: https://blog.sunansheng.com

# 自定义post url
permalink: /article/:title.html
timezone: Asia/Chongqing

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
gems:
  - jekyll-sitemap
